name: fedlexplorer
description: The purpose of this project is to demonstrate how Swiss federal legislation
  data can be used in third-party products through a SPARQL endpoint.
publish_to: 'none'

version: 0.0.2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  web:
    generate: true
  macos:
    generate: true
  ios: true
  image_path: "assets/ch.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
